// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	dto "discusiin/dto"

	mock "github.com/stretchr/testify/mock"
)

// IBookmarkServices is an autogenerated mock type for the IBookmarkServices type
type IBookmarkServices struct {
	mock.Mock
}

// AddBookmark provides a mock function with given fields: token, postID
func (_m *IBookmarkServices) AddBookmark(token dto.Token, postID int) error {
	ret := _m.Called(token, postID)

	var r0 error
	if rf, ok := ret.Get(0).(func(dto.Token, int) error); ok {
		r0 = rf(token, postID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteBookmark provides a mock function with given fields: token, postID
func (_m *IBookmarkServices) DeleteBookmark(token dto.Token, postID int) error {
	ret := _m.Called(token, postID)

	var r0 error
	if rf, ok := ret.Get(0).(func(dto.Token, int) error); ok {
		r0 = rf(token, postID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllBookmark provides a mock function with given fields: token
func (_m *IBookmarkServices) GetAllBookmark(token dto.Token) ([]dto.PublicBookmark, error) {
	ret := _m.Called(token)

	var r0 []dto.PublicBookmark
	if rf, ok := ret.Get(0).(func(dto.Token) []dto.PublicBookmark); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.PublicBookmark)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(dto.Token) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewIBookmarkServices interface {
	mock.TestingT
	Cleanup(func())
}

// NewIBookmarkServices creates a new instance of IBookmarkServices. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIBookmarkServices(t mockConstructorTestingTNewIBookmarkServices) *IBookmarkServices {
	mock := &IBookmarkServices{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
