name: CI
on:
  push:
    branches:
      - "development"
jobs:
  testing:
    runs-on: ubuntu-latest
    name: "unit-test"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: run unit test
        run: go test -v ./...
  linting:
    runs-on: ubuntu-latest
    name: "linting"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: run linting
        uses: golangci/golangci-lint-action@v3